### ISSUE TITLE
The Stuffed Fish

### ISSUE THREAD

**Issue by hrc2021** [ccrgoalie9/LIDUSCGASE#33]
GET IT

**Comment by hrc2021** [comment]
![image](https://user-images.githubusercontent.com/45672808/68499889-64b8c700-0228-11ea-8b37-f57173f9a68a.png)

**Comment by hrc2021** [comment]
We ordered a stuffed polar bear

**Comment by CarbonCGAutonomous** [comment]
Stuffed Polar Bear in by Thursday
