### ISSUE TITLE
I got issues!

### ISSUE THREAD

**Issue by ethangoldcga** [ccrgoalie9/LIDUSCGASE#36]
More issues than the X-men

Also, I need some ice for a drink. This application isn't delivering ice fast enough, and my drink is warming up in my computer's cup-holder.

Q: Why did the programmer die in the shower?
A: The instructions on the shampoo said: "Lather, rinse, repeat."

**Comment by CarbonCGAutonomous** [comment]
Issue clearly exists between keyboard and chair. Issue is closed.
